# Generated by Django 3.0.8 on 2020-07-19 14:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=100)),
                ('state', localflavor.us.models.USStateField(default='NA', max_length=2, verbose_name='state')),
                ('city', models.CharField(default='NA', max_length=64, verbose_name='city')),
                ('address', models.CharField(default='NA', max_length=128, verbose_name='address')),
                ('zip_code', models.CharField(default='00000', max_length=5, verbose_name='zip code')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='CourseHoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfHoles', models.IntegerField(default=0)),
                ('parList', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='home.Course')),
            ],
        ),
    ]
