# Generated by Django 3.0.3 on 2020-07-24 18:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200723_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scoreList',
            field=models.CharField(max_length=27, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
