# Generated by Django 3.0.3 on 2020-07-30 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200728_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='game',
            name='date_edited',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
