# Generated by Django 3.0.3 on 2020-08-24 14:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_game_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseholes',
            name='distList',
            field=models.CharField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], max_length=27, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
