# Generated by Django 3.0.3 on 2020-08-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_courseholes_distlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
